enum Region {
  AfSouth1 = 'af-south-1',
  ApEast1 = 'ap-east-1',
  ApNorthEast1 = 'ap-northeast-1',
  ApNorthEast2 = 'ap-northeast-2',
  ApNorthEast3 = 'ap-northeast-3',
  ApSouth1 = 'ap-south-1',
  ApSouthEast1 = 'ap-southeast-1',
  ApSouthEast2 = 'ap-southeast-2',
  CaCentral1 = 'ca-central-1',
  EuCentral1 = 'eu-central-1',
  EuNorth1 = 'eu-north-1',
  EuSouth1 = 'eu-south-1',
  EuWest1 = 'eu-west-1',
  EuWest2 = 'eu-west-2',
  EuWest3 = 'eu-west-3',
  MeSouth1 = 'me-south-1',
  SaEast1 = 'sa-east-1',
  UsEast1 = 'us-east-1',
  UsEast2 = 'us-east-2',
  UsWest1 = 'us-west-1',
  UsWest2 = 'us-west-2',
}

export default Region;
